spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          autoCreateTopics: false
          configuration:
            commit:
              interval:
                mms: 1000
            default:
              key:
                serde:  org.apache.kafka.common.serialization.Serdes$StringSerde
              value:
                serde:  org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        customers-in:
          destination: customer
          contentType: application/json
          group: customers_group
          consumer:
            header-mode: raw
        customers-out:
          destination: customer
          contentType: application/json
          group: customers_group
          consumer:
            header-mode: raw

        orders-in:
          destination: order
          contentType: application/json
          group: orders_group
          producer:
            header-mode: raw
        orders-out:
          destination: order
          contentType: application/json
          group: orders_group
          producer:
            header-mode: raw

        greetings-in:
          destination: greetings
          contentType: application/json
          group: greetings_group
          producer:
            header-mode: raw
        greetings-out:
          destination: greetings
          contentType: application/json
          group: greetings_group
          producer:
            header-mode: raw


server:
  port: ${PORT:8090}