spring:	
  cloud:	
    stream:	
      kafka:	
        binder:	
          brokers: localhost:9092	
          autoCreateTopics: false	
          configuration:	
            commit:	
              interval:	
                mms: 1000
      bindings:	
        customersin:	
          destination: customer	
          contentType: application/json	
          group: customers_group	
          consumer:	
            headermode: raw	
        customersout:	
          destination: customer	
          contentType: application/json	
          group: customers_group	
          consumer:	
            headermode: raw	
	
        ordersin:	
          destination: order	
          contentType: application/json	
          group: orders_group	
          producer:	
            headermode: raw	
        ordersout:	
          destination: order	
          contentType: application/json	
          group: orders_group	
          producer:	
            headermode: raw	
	
        greetingsin:	
          destination: greetings	
          contentType: application/json	
          group: greetings_group	
          producer:	
            headermode: raw	
        greetingsout:	
          destination: greetings	
          contentType: application/json	
          group: greetings_group	
          producer:	
            headermode: raw
server:
  port: ${PORT:8090}